cellType: bacilli
timestep:   1.0   # second
maxSpeed:  24.0   # microns per second
maxSpin:    1.57  # radians per second
minGrowth: -2.0   # microns
maxGrowth:  13.0   # microns
minWidth:   1.0   # microns
maxWidth:   14.0   # microns
minLength: 13.0   # microns
maxLength: 32.0   # microns
delimiter: " "
---
name      x     y   width  length  rotation
1     132   127       9      29      4.15
2     168   106       9      25      1.91
